// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9K065Z8RcjU7GTtR7buIhPrayCPjYC2U',
    appId: '1:202253246155:web:d403842acaac62b677854e',
    messagingSenderId: '202253246155',
    projectId: 'messageme-bb72c',
    authDomain: 'messageme-bb72c.firebaseapp.com',
    storageBucket: 'messageme-bb72c.appspot.com',
    measurementId: 'G-488C17DFJY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuk9DFYxiqaejMWtozygXSRim6mkV_taM',
    appId: '1:202253246155:android:aa4df0b4c9a7df7c77854e',
    messagingSenderId: '202253246155',
    projectId: 'messageme-bb72c',
    storageBucket: 'messageme-bb72c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAL4Xmwvw88Ot4W7LeozqILtHgbeWOqYM',
    appId: '1:202253246155:ios:bfe33f34e9326bd777854e',
    messagingSenderId: '202253246155',
    projectId: 'messageme-bb72c',
    storageBucket: 'messageme-bb72c.appspot.com',
    androidClientId: '202253246155-cmqkalsopqdt0p3vp2oo59seqi7u43ro.apps.googleusercontent.com',
    iosClientId: '202253246155-752kqgm1t1bcstf9jmhnklfi827pkvnk.apps.googleusercontent.com',
    iosBundleId: 'com.glare.messagess',
  );
}
